fix: validates selecting two phonemes
wordification/app pull request #151
Opened 2023-11-01 00:09 UTC by jrginn

2023-11-08 03:47 UTC, claycrews2002 requested changes

2023-11-08 03:47 UTC, claycrews2002 commented on api/src/services/gameSetups/gameSetups.ts
> +  validate(selected, { acceptance: {in: [true], message: 'You must select exactly two phonemes or some graphemes!'}})
Make sure you're using ESLint on your code for readability. This should look like:
```
validate(selected, {
    acceptance: {
      in: [true],
      message: 'You must select exactly two phonemes or some graphemes!',
    },
  })
```

2023-11-08 03:47 UTC, claycrews2002 commented on api/src/services/gameSetups/gameSetups.ts
> +  if (phonemes.length > 0) {
This was still causing the site to need a refresh every time two phonemes weren't selected... I think it has to do with the `throw new error()` bit.

Make this entire if-statement look like this and it should work:
```
if (phonemes.length > 0) {
    validate(phonemes.length, 'phoneme length', {
      numericality: {
        equal: 2,
        message: 'You must select exactly two phonemes!',
      },
    })
    validate(phonemes, 'phonemes', {
      custom: {
        with: async () => {
          const dbPhonemes = await db.phoneme.findMany()
          const allowedPhonemes = dbPhonemes.flatMap((p) => p.id)
          phonemes.forEach((phoneme) => {
            if (!allowedPhonemes.includes(phoneme)) {
              const allowedPhonemeNames = dbPhonemes.flatMap((p) => p.name)
              throw new Error(
                `Invalid phonemes selected! Allowed Phonemes: ${allowedPhonemeNames.join(
                  ', '
                )}`
              )
            }
          })
        },
      },
    })
  }
```

2023-11-09 18:30 UTC, jrginn reviewed
looks good

2023-11-09 19:35 UTC, merged