164 screen re design
wordification/app pull request #182
Opened 2024-04-11 14:49 UTC by ShashComandur

Pending small changes to Teacher layout, but this is largely what the UI changes to student view will look like.

2024-04-12 12:11 UTC, claycrews2002 requested changes

2024-04-12 12:11 UTC, claycrews2002 commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
I always fight with this setting. It auto corrects to `"explicit"` when it should be `true` but fights on it being true... maybe should be `"always"`
Possibly the reason eslint errors aren't auto-fixed in your code here.

Still need to figure this out, but in the meantime change back to true and disregard the change if it makes it again please.

2024-04-12 12:11 UTC, claycrews2002 commented on web/config/tailwind.config.js
> +        'sans': ['"Proxima Nova"', ...defaultTheme.fontFamily.sans],
Are we using this font or the `Gabarito` font?

2024-04-12 12:11 UTC, claycrews2002 commented on web/config/tailwind.config.js
> +    themes: [
Slightly confused.. did you figure out how to define our own theme? Or are we using the colors defined in the `index.css` ? Just curious

2024-04-12 12:46 UTC, ShashComandur commented on web/config/tailwind.config.js
> +    themes: [
using the ones defined in index.css. the stuff in the tailwindconfig (both instances of the file) are, from understanding, not used.

2024-04-12 13:26 UTC, ShashComandur commented on web/config/tailwind.config.js
> +    themes: [
The individual colors are not used, but the navbar background definition relies on the theme. I'm including it here still because it's a semantic way to update the properties of a single component.

2024-04-12 13:30 UTC, ShashComandur commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
I think the reason you're experiencing some wonky behavior here is that the `.vscode` folder is not included in `.gitignore`, so whenever someone commits to the repo with their person `settings.json` different from yours, it gets overwritten. 

I've changed it to `true` and also added `.vscode` to the `.gitignore` file.

2024-04-12 13:31 UTC, ShashComandur commented on web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx
> +            className="card shadow-lg hover:shadow-xl bg-off-black"
I do not, but I changed the `.settings.json` to what you mentioned in the other comment. Not sure if that's what is supposed to fix this though. We should try to figure out how to get prettier working for everyone.

2024-04-12 13:35 UTC, claycrews2002 commented on web/src/pages/AdminDashboardPage/AdminDashboardPage.tsx
> +            className="card shadow-lg hover:shadow-xl bg-off-black"
I think it might be how vscode is setup on my machine. Dalton set it up way back for Capstone. We'll take a look.

2024-05-18 15:41 UTC, claycrews2002 approved these changes

2024-05-18 15:41 UTC, merged